-- V1 — Schéma initial. Reflète exactement docs/diagrammes/D2-modele-donnees.md.
-- Toutes les dates sont en UTC (ENF7).

CREATE TABLE promotion (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(100) NOT NULL,
    promotion_id  BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE TABLE session_cours (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(200) NOT NULL,
    promotion_id   BIGINT NOT NULL,
    code           VARCHAR(6) NOT NULL,
    ouverture_at   TIMESTAMP NOT NULL,
    expiration_at  TIMESTAMP NOT NULL,
    cloturee_at    TIMESTAMP,
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id),
    CONSTRAINT uk_session_code UNIQUE (code)                                   -- RG20
);

CREATE TABLE presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    etudiant_id  BIGINT NOT NULL,
    source       VARCHAR(10) NOT NULL,
    marquee_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),  -- RG3
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')) -- RG15
);

CREATE TABLE tentative_code (
    etudiant_id         BIGINT PRIMARY KEY,
    echecs_consecutifs  INT NOT NULL DEFAULT 0,                                -- RG4
    bloque_jusqu_a      TIMESTAMP,
    CONSTRAINT fk_tentative_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

CREATE TABLE exercice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    etudiant_id  BIGINT NOT NULL,
    lien         VARCHAR(500) NOT NULL,                                        -- RG18
    statut       VARCHAR(25) NOT NULL,
    depose_at    TIMESTAMP NOT NULL,
    modifie_at   TIMESTAMP,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),  -- RG13
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU'))
);

CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL,
    relecteur_id  BIGINT NOT NULL,
    note          INT,
    commentaire   VARCHAR(2000),
    statut        VARCHAR(15) NOT NULL,
    assignee_at   TIMESTAMP NOT NULL,
    modifiee_at   TIMESTAMP,
    rendue_at     TIMESTAMP,
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id),
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),                     -- RG6
    CONSTRAINT ck_relecture_note CHECK (note BETWEEN 0 AND 20),                -- RG9
    CONSTRAINT ck_relecture_statut CHECK (statut IN ('A_FAIRE', 'BROUILLON', 'RENDUE'))
);

CREATE INDEX ix_etudiant_promotion ON etudiant (promotion_id);
CREATE INDEX ix_session_promotion ON session_cours (promotion_id);
CREATE INDEX ix_relecture_relecteur ON relecture (relecteur_id);
